In [1]:
import numpy as np
import pandas as pd

데이터를 분석하려면 데이터 프레임 형태로 만들면 됨  
행(인스턴스, 실제값), 열(속성, 특성)을 가지는 2차원이  되도록 함  
파이선에서는 데이터 분석시 사용하는 2차원의 데이터를 다루기 위해서 클래스(부품)을 만들었다.  

In [2]:
# 딕셔너리
name_values=["홍길동",'박길동','김길동','송길동']
age_values=[10,20,30,40]
#dics ={"name" : name_values, 'age' : age_values}
df = pd.DataFrame({"name" : name_values, 'age' : age_values})
df

name  age
0  홍길동   10
1  박길동   20
2  김길동   30
3  송길동   40

In [3]:
# 인덱스가 자동 증가해서  붙어있는 부품: 데이터 프레임
df.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
df_index = df.index.tolist()  # 인덱스만 목록으로 가지고 오고 싶으면 tolist를 사용해라!!
df_index

[0, 1, 2, 3]

In [5]:
# RangeIndex 부품, class
type(df.index)

pandas.core.indexes.range.RangeIndex

In [6]:
df['name']

0    홍길동
1    박길동
2    김길동
3    송길동
Name: name, dtype: object

In [7]:
type(df['name'])

pandas.core.series.Series

In [8]:
df.name

0    홍길동
1    박길동
2    김길동
3    송길동
Name: name, dtype: object

In [9]:
# 시리즈를 데이터 프레임으로 변경할 수 있다.
df_name = df['name'].to_frame()
print(type(df_name))
df_name

<class 'pandas.core.frame.DataFrame'>


name
0  홍길동
1  박길동
2  김길동
3  송길동

In [10]:
# 데이터프레임은 RangeIndex, Series의 결합

In [11]:
# 시리즈는 인덱스와 array의 결합

In [12]:
df['name'].index

RangeIndex(start=0, stop=4, step=1)

In [13]:
df_name_list = df['name'].index.tolist()
df_name_list

[0, 1, 2, 3]

In [14]:
df['name'].values

array(['홍길동', '박길동', '김길동', '송길동'], dtype=object)

In [15]:
df_name_values = df['name'].values.tolist()
df_name_values

['홍길동', '박길동', '김길동', '송길동']

## 데이터 프레임을 만드는 방법
***
1. dic사용
2. csv, excel 파일 읽어오기
3. df에 values, columns을 지정

In [17]:
df2 = pd.DataFrame(data= [['홍길동', 100],['김길동', 200]],columns=['name','age'])
df2

name  age
0  홍길동  100
1  김길동  200

In [19]:
type(df2.columns)

pandas.core.indexes.base.Index

In [20]:
df2.columns

Index(['name', 'age'], dtype='object')

In [21]:
df2.columns.tolist()

['name', 'age']

In [23]:
data = [100,200,300] # 1차원인 리스트
sum(data)

600

In [24]:
print(min(data))
max(data)

100


300

In [26]:
len(data)

3

In [28]:
np.sum(data)

600

In [30]:
np.mean(data)

200.0

In [31]:
# ndarray : 다양한 차원의 데이터(배열)를 하나의 클래스로 다루기 위해 만들어졌음
# n: 숫자
# d: 차원(dimension)
# array: 배열

In [34]:
arr1 = np.arange(15) # 0~14까지의 연속된 값을 만들어주는 함수
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [38]:
arr1_reshape = arr1.reshape(3,5) # 원하는 차원(모양)으로 변환
arr1_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
type(arr1_reshape)

numpy.ndarray

In [40]:
# 2차원 배열(행렬)의 사용 예제 => 자동차 번호판 인식을 할때 2차원의 그림을 마스킹을해서(구역별로 나눔)
# 구별을하도록 해준다

In [42]:
# mask
mask = np.zeros(5)
mask

array([0., 0., 0., 0., 0.])

In [43]:
mask2 = np.zeros((3,5))
mask2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
arr2 = np.array([
    [1,2,3],[4,5,6]
],dtype=np.float64)   # 컴퓨터가 64비트이기 때문에 float64를 해줌
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [46]:
arr3 = np.array([
    [7,8,9],[10,11,12]
],dtype=np.float64)   # 컴퓨터가 64비트이기 때문에 float64를 해줌
arr3

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [47]:
# 행렬의 연산을 할 수 있음
arr2 + arr3

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [48]:
arr3 - arr2

array([[6., 6., 6.],
       [6., 6., 6.]])

In [49]:
arr2 * arr3

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [50]:
np.random.rand(20)

array([0.26051393, 0.13270571, 0.24411856, 0.05011432, 0.08668261,
       0.01457719, 0.12717657, 0.79990634, 0.5640373 , 0.13456482,
       0.23297349, 0.49508017, 0.26736414, 0.07886701, 0.65276003,
       0.88537264, 0.4954922 , 0.49244984, 0.81308841, 0.43019413])